name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: golang:1.20-bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags="-s -w" -o go-vod-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -buildvcs=false -ldflags="-s -w" -o go-vod-arm64

      - name: Upload to releases
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          file: go-vod-*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
