---
name: static analysis
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'go-vod/**'
      - 'android/**'
      - 'mkdocs.yml'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'go-vod/**'
      - 'android/**'
      - 'mkdocs.yml'
      - '**.md'

jobs:
  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: nextcloud/server
          ref: stable27

      - name: Checkout the app
        uses: actions/checkout@v3
        with:
          path: apps/memories

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl
          coverage: none

      - name: Install dependencies
        working-directory: apps/memories
        run: |
          make install-tools

      - name: Run Psalm
        working-directory: apps/memories
        run: |
          vendor/bin/psalm --no-cache --shepherd --stats --threads=max lib

      - name: Run PHP-CS-Fixer
        working-directory: apps/memories
        run: |
          vendor/bin/php-cs-fixer fix --dry-run --diff

  vue-lint:
    name: Vue Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run vue-tsc
        run: npx vue-tsc --noEmit --skipLibCheck

      - name: Run Prettier
        run: npx prettier src --check
